apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-app-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/jaehanbyun/argo-orphaned-resource-test.git
  destinations:
    - namespace: "orphaned"
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
