apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
  namespace: argocd
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/jaehanbyun/argo-orphaned-resource-test.git
    path: argocd-example-app/application
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
